version: "3"
services:
        jenkins:
                # image: blueocean_plugin:v0.1
                build: ./
                        # context:./
                        # # dockerfile:dockerfile
                image: blueocean_plugin:latest
                        # - context: /work/FyJenkins/jenkins-server
                        # - dockerfile:/work/jenkins/Dockerfile
                volumes:
                        - jenkins-data-plugin:/var/jenkins_home
                        - /var/run/docker.sock:/var/run/docker.sock

                ports:
                        - "7088:8080"
                        - "50000:50000"
                expose:
                        - "7088"
                        - "50000"
                privileged: true
                user: root
                restart: always
                container_name: jenkins-blueocean-plugin
volumes:
        jenkins-data-plugin:

#docker-compose up -d
#chown -R 1000:1000 /data/jenkins
