FROM jenkinsci/blueocean:latest
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
ENV JENKINS_UC https://mirrors.tuna.tsinghua.edu.cn
ENV JENKINS_UC_DOWNLOAD https://mirrors.tuna.tsinghua.edu.cn/jenkins
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
#RUN sed -i 's/<url>*/<url>https:\/\/mirrors.tuna.tsinghua.edu.cn\/jenkins\/updates\/update-center.json1<\/url>/g'  /var/jenkins_home/hudson.model.UpdateCenter.xml