version: '3.3'
services: 
  web:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: '202.127.204.194'
    environment:
      # - GITLAB_HOME=/srv/gitlab/
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://202.127.204.194:8930'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.163.com"
        gitlab_rails['smtp_port'] = 25
        gitlab_rails['smtp_user_name'] = "liuxj11683@163.com"
        gitlab_rails['smtp_password'] = "SRWOBCWVJTGZYZEQ"
        gitlab_rails['smtp_domain'] = "smtp.163.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['gitlab_email_from'] = 'liuxj11683@163.com'
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        ### Email Settings
        gitlab_rails['gitlab_email_enabled'] = true
        gitlab_rails['gitlab_email_from'] = 'liuxj11683@163.com'   ## 发件邮箱
        gitlab_rails['gitlab_email_display_name'] = 'git server'  ## 显示名字
    ports:
      - '8930:8930'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks: 
      - gitlab

networks: 
  gitlab:


### docker-compose --env-file ./config/.env.dev up 